baseURL = "https://hackliza.gal/"
languageCode = "gl"
title = "Hackliza"
theme = "beautifulhugo"

DefaultContentLanguage = "gl"

publishDir = "docs"

[Params]
subtitle = "Hacking na Galiza"
logo = "img/hackliza.png"
favicon = "img/hackliza.png"
rss = true

[languages]
[languages.gl]
contentDir = "content/gl"

[languages.en]
contentDir = "content/en"


[[menu.main]]
name = "About"
url = "page/about/"
