baseURL = "https://hackliza.gal/"
languageCode = "gl"
title = "Hackliza"
theme = "beautifulhugo"

disqusShortname = "hackliza"
DefaultContentLanguage = "gl"

[Params]
subtitle = "Unha comunidade en galego sobre software libre, programación, (in)seguridade informática e outras herbas."
logo = "img/hackliza.png"
favicon = "img/hackliza.png"
rss = true
readingTime = true
comments = true


[Author]
github = "hackliza"
twitter = "hackliza"

[languages]
[languages.gl]
contentDir = "content/gl"

[languages.en]
contentDir = "content/en"

