baseURL = "https://hackliza.gal/"
languageCode = "gl"
title = "Hackliza"
theme = "beautifulhugo"

disqusShortname = "hackliza"
DefaultContentLanguage = "gl"

[Params]
subtitle = "Unha comunidade en galego sobre software libre, programación, (in)seguridade informática e outras herbas."
logo = "img/hackliza.png"
favicon = "img/hackliza.png"
rss = true
readingTime = true
comments = true


[Author]
github = "hackliza"
twitter = "hackliza"

[languages]
[languages.gl]
contentDir = "content/gl"
    [languages.gl.menus]
        [[languages.gl.menus.main]]
        name = "Charlas"
        url = "talks/"
        weight = 3
        [[languages.gl.menus.main]]
        name = "Sobre nós"
        url = "about/"
        weight = 2
        [[languages.gl.menus.main]]
        name = "Blogue"
        url = "/"
        weight = 1

[languages.en]
contentDir = "content/en"
    [languages.en.menus]
        [[languages.en.menus.main]]
        name = "Talks"
        url = "talks/"
        weight = 3

        [[languages.en.menus.main]]
        name = "About"
        url = "about/"
        weight = 2
        [[languages.en.menus.main]]
        name = "Blog"
        url = "/"
        weight = 1